import { FrameData } from "./types";

export const BLAST_FRAMES: FrameData[] = [
  {
    text: "Embrace the lush",
    wordCount: 3,
    time: 0.53,
    selected: false,
    backgroundColor: "white",
    textColor: "black",
  },
  {
    text: "green",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "canopies",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "of",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "Karnataka's",
    wordCount: 1,
    time: 0.27,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "forests home to majestic",
    wordCount: 4,
    time: 0.51,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "tigers 🐅 vibrant",
    wordCount: 3,
    time: 0.75,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "elephants",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "🐘",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "and diverse bird",
    wordCount: 3,
    time: 0.77,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "species",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "🦜",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "Let's unite to",
    wordCount: 3,
    time: 0.74,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "safeguard these precious",
    wordCount: 3,
    time: 0.77,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "habitats",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "preserving",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "the",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "delicate balance of",
    wordCount: 3,
    time: 0.76,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "nature and protecting",
    wordCount: 3,
    time: 0.59,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "our",
    wordCount: 1,
    time: 0.22,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "wildlife",
    wordCount: 1,
    time: 0.2,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "for",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "generations",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "to",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "come",
    wordCount: 1,
    time: 0.27,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "Together we can",
    wordCount: 3,
    time: 0.97,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "be",
    wordCount: 1,
    time: 0.29,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "the",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "voice for the",
    wordCount: 3,
    time: 0.51,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "voiceless",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "and",
    wordCount: 1,
    time: 0.27,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "ensure a harmonious",
    wordCount: 3,
    time: 0.75,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "coexistence",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "with our natural",
    wordCount: 3,
    time: 0.5,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "world Let's protect",
    wordCount: 3,
    time: 0.5,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "Karnataka's forests and",
    wordCount: 3,
    time: 1.01,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "wildlife",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "our shared heritage",
    wordCount: 3,
    time: 0.52,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "our responsibility",
    wordCount: 3,
    time: 0.45,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
];
export const BLAST_AUDIO = "blast.mp3";

/**
 * 0.4 - Branding
 * 0.5 - is
 * 0.9 - the
 * 1.1 - overall
 * 1.25 - overall
 * 1.4 - overall
 * 1.55 - overall
 * 1.75 - overall
 * 2.2 - experience
 * 2.4 - you
 * 2.9 - you
 * 3.2 - you
 * 3.5 - for
 * 3.65 - for
 * 4.1 - your
 * 4.2 - audience
 * 4.7 - audience
 * 5.15 - that
 * 5.4 - truly
 * 5.6 - truly
 * 6.0 - stand
 * 6.2 - out
 * 6.5 - out
 * 6.65 - and
 * 7.15- your
 * 7.75 - brand
 * 8.0 - to
 * 8.65 - connect
 * 8.9 - with
 * 9.55 - audience
 * 9.95 - on
 * 10.1 - a
 * 10.5 - deeper
 * 10.75 - deeper
 * 11.32 - level
 * 11.85 - 😌
 */

export const BRAND_FRAMES: FrameData[] = [
  {
    text: "Branding",
    wordCount: 1,
    time: 0.4,
    selected: false,
    type: "font-size",
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "is",
    wordCount: 1,
    time: 0.1,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "the",
    wordCount: 1,
    time: 0.4,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "overall",
    wordCount: 1,
    time: 0.2,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "overall",
    wordCount: 1,
    time: 0.15,
    selected: false,
    backgroundColor: "#000000", // swapped
    textColor: "#ffffff",
  },
  {
    text: "overall",
    wordCount: 1,
    time: 0.15,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "overall",
    wordCount: 1,
    time: 0.15,
    selected: false,
    backgroundColor: "#000000",
    textColor: "#ffffff",
  },
  {
    text: "overall",
    wordCount: 1,
    time: 0.2,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "experience",
    wordCount: 1,
    time: 0.45,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "you",
    wordCount: 1,
    time: 0.2,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "you",
    wordCount: 1,
    time: 0.5,
    selected: false,
    backgroundColor: "#000000",
    textColor: "#ffffff",
  },
  {
    text: "create",
    wordCount: 1,
    time: 0.3,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "for",
    wordCount: 1,
    time: 0.3,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "for",
    wordCount: 1,
    time: 0.15,
    selected: false,
    backgroundColor: "#000000",
    textColor: "#ffffff",
  },
  {
    text: "your",
    wordCount: 1,
    time: 0.45,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "audience",
    wordCount: 1,
    time: 0.6,
    selected: false,
    type: "font-size",
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "that",
    wordCount: 1,
    time: 0.45,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "truly",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "truly",
    wordCount: 1,
    time: 0.2,
    selected: false,
    backgroundColor: "#000000",
    textColor: "#ffffff",
  },
  {
    text: "stand",
    wordCount: 1,
    time: 0.4,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "out",
    wordCount: 1,
    time: 0.2,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "out",
    wordCount: 1,
    time: 0.3,
    selected: false,
    backgroundColor: "#000000",
    textColor: "#ffffff",
  },
  {
    text: "and",
    wordCount: 1,
    time: 0.15,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "your",
    wordCount: 1,
    time: 0.5,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "brand",
    wordCount: 1,
    time: 0.6,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "to",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "connect",
    wordCount: 1,
    time: 0.65,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "with",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "audience",
    wordCount: 1,
    time: 0.65,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "on",
    wordCount: 1,
    time: 0.4,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "a",
    wordCount: 1,
    time: 0.15,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "deeper",
    wordCount: 1,
    time: 0.4,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "deeper",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#000000",
    textColor: "#ffffff",
  },
  {
    text: "level",
    wordCount: 1,
    time: 0.1,
    type: "text-one",
    fontSize: 32,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "level",
    wordCount: 1,
    time: 0.1,
    type: "text-one",
    fontSize: 28,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "level",
    wordCount: 1,
    time: 0.1,
    type: "text-one",
    fontSize: 24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "level",
    wordCount: 1,
    time: 0.1,
    type: "text-one",
    fontSize: 20,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "level",
    wordCount: 1,
    time: 0.17,
    type: "text-one",
    fontSize: 18,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "😌",
    wordCount: 1,
    time: 0.53,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
];

export const BRAND_AUDIO = "brand.mp3";
