import { FrameData } from "./types";

export const BLAST_FRAMES: FrameData[] = [
  {
    text: "Embrace the lush",
    wordCount: 3,
    time: 0.53,
    selected: false,
    backgroundColor: "white",
    textColor: "black",
  },
  {
    text: "green",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "canopies",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "of",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "Karnataka's",
    wordCount: 1,
    time: 0.27,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "forests home to majestic",
    wordCount: 4,
    time: 0.51,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "tigers 🐅 vibrant",
    wordCount: 3,
    time: 0.75,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "elephants",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "🐘",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "and diverse bird",
    wordCount: 3,
    time: 0.77,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "species",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "🦜",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "Let's unite to",
    wordCount: 3,
    time: 0.74,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "safeguard these precious",
    wordCount: 3,
    time: 0.77,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "habitats",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "preserving",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "the",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "delicate balance of",
    wordCount: 3,
    time: 0.76,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "nature and protecting",
    wordCount: 3,
    time: 0.59,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "our",
    wordCount: 1,
    time: 0.22,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "wildlife",
    wordCount: 1,
    time: 0.2,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "for",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "generations",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "to",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "come",
    wordCount: 1,
    time: 0.27,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "Together we can",
    wordCount: 3,
    time: 0.97,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "be",
    wordCount: 1,
    time: 0.29,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "the",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "voice for the",
    wordCount: 3,
    time: 0.51,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "voiceless",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "and",
    wordCount: 1,
    time: 0.27,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "ensure a harmonious",
    wordCount: 3,
    time: 0.75,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "coexistence",
    wordCount: 1,
    time: 0.25,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "with our natural",
    wordCount: 3,
    time: 0.5,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "world Let's protect",
    wordCount: 3,
    time: 0.5,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "Karnataka's forests and",
    wordCount: 3,
    time: 1.01,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "wildlife",
    wordCount: 1,
    time: 0.24,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "our shared heritage",
    wordCount: 3,
    time: 0.52,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
  {
    text: "our responsibility",
    wordCount: 3,
    time: 0.45,
    selected: false,
    backgroundColor: "#ffffff",
    textColor: "#000000",
  },
];
export const BLAST_AUDIO = "blast.mp3";
